name: test-and-publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dashboard
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        git clone https://github.com/userdashboard/dashboard.git /tmp/instance
        cd /tmp/instance
        npm install mysql2 mocha faker puppeteer@2.1.1 --no-save
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
    - name: Increase NPM version
      run: npm version patch
    - name: Fake-install module
      run: |
        mkdir -p /tmp/instance/node_modules/@userdashboard/storage-mysql
        cp index.js /tmp/instance/node_modules/@userdashboard/storage-mysql
        cp setup.sql /tmp/instance/node_modules/@userdashboard/storage-mysql
        cp -R src /tmp/instance/node_modules/@userdashboard/storage-mysql
    - name: Test unencrypted MySQL storage
      run: cd /tmp/instance && npm test
      env:
        NODE_ENV: testing
        FAST_START: "true"
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-mysql"
        DATABASE_URL: "mysql://root:password@127.0.0.1:8888/dashboard"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
    - name: Test encrypted MySQL storage
      run: cd /tmp/instance && npm test
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-mysql"
        DATABASE_URL: "mysql://root:password@127.0.0.1:8888/dashboard"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
